import "server_auth.proto";
import "server_control.proto";

package protocol;

message ServerMessage {
  oneof body {
    server_control.ShutdownServerResponse shutdown_server_response = 1;
    server_control.RestartServerResponse restart_server_response = 2;

    server_control.ActiveGameServerResponse active_game_server_response = 11;
    server_control.DeactiveGameServerResponse deactive_game_server_response = 12;
    server_control.DisconnectAllGameClientsResponse disconnect_all_game_clients_response = 13;

    admin_auth.LoginSuccessResponse login_success_response = 101;
    admin_auth.LoginFailureResponse login_failure_response = 102;
  }
}
