
syntax = "proto3";

package users_management;

message UsersListRequest {
    string filter_name = 1;
    int32 sort_type = 2;
    uint64 last_id = 3;
    uint64 max_count = 4;
}

message UserData {
    int64 id = 1;
    int32 type = 2;
    string username = 3;
    string display_name = 4;
    string api_token = 5;
    int32 last_online_at = 6;
    bool is_banned = 7;
    string ban_reason = 8;
    int32 banned_until = 9;
    bool is_actived = 10;
}

message UsersListSuccessResponse {
    repeated UserData users = 1;
}

message UsersListFailureResponse {
    string reason = 1;
}

message GroupsListRequest {}

message GroupData {
    int64 id = 1;
    bool is_system = 2;
    string name = 3;
    string display_name = 4;
    string desc = 5;
    bool is_actived = 6;
}

message GroupsListSuccessResponse {
    repeated GroupData groups = 1;
}

message GroupsListFailureResponse {
    string reason = 1;
}

message RolesListRequest {}

message RoleData {
    int64 id = 1;
    bool is_system = 2;
    string name = 3;
    string display_name = 4;
    string desc = 5;
    bool is_actived = 6;
}

message RolesListSuccessResponse {
    repeated RoleData roles = 1;
}

message RolesListFailureResponse {
    string reason = 1;
}

message PermissionsListRequest {}

message PermissionData {
    int32 risk_level = 1;
    string name = 2;
    string desc = 3;
}

message PermissionsListSuccessResponse {
    repeated PermissionData permissions = 1;
}

message PermissionsListFailureResponse {
    string reason = 1;
}
